name: Deploy

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    strategy:
      matrix:
        version: [1.0]

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker
        run: docker build -t yourname/app:${{ matrix.version }} .

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Push
        run: docker push yourname/app:${{ matrix.version }}