name: 29917_deploy

on:
  workflow_run:
    workflows: ["29917_test"]
    types:
      - completed

jobs:
  deploy:
    # zaženi samo če je test workflow uspešen
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      # checkout kode
      - name: Checkout kode
        uses: actions/checkout@v4

      # IZKLOP BuildKit (ker nimaš buildx)
      - name: Disable BuildKit
        run: echo "DOCKER_BUILDKIT=0" >> $GITHUB_ENV

      # prijava v DockerHub
      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # build Docker image
      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/calculator:latest .

      # push na DockerHub
      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/calculator:latest