name: Tests

on:
  push:
    branches: [ main ]

jobs:
  check-tests:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Check tests
        run: |
          if [ ! -f test.sh ]; then
            echo "Ni testov" 2> napaka.txt
          else
            touch napaka.txt
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: napaka
          path: napaka.txt

  run-tests:
    runs-on: self-hosted
    needs: check-tests

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: napaka

      - name: Check napaka.txt
        run: |
          if [ -s napaka.txt ]; then
            echo "Napaka obstaja"
            exit 1
          fi

      - name: Run tests
        run: |
          chmod +x test.sh
          ./test.sh