name: 29917_deploy

on:
  workflow_run:
    workflows: ["29917_test"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/calculator:latest .

      - name: Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/calculator:latest